#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path


b. He flys like a bird and flaps his wings


c. He levitates, he's an alien "HEELLLLLOOOO!"


d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!

statment = p \rightarrow q

Contrapositive
~q \rightarrow ~p
Converse
q \rightarrow p
inverse
~p \rightarrow ~q
R: real numbers
All numbers that are not imaginary
Z: integers
Any number without a decimal or fraction.
Q: rational numbers
Numbers that can be displayed as a fraction. not numbers like π or e
predicate
Functions that return a boolian value
Domain

CoDomain

quantifier

antecedent
The p in our above statement. Also known as the hypothese.
consequent
The q in our above statement. also know as the conclusion.
Set
A collection of objects, numbers, or words.
Fallacy
Someting that is not logically equivalent. 
biconditional
Similar to the logic XOR and iff. true when p and q are the same but false when
the are different.
sufficient condition
the apearance of a true antecedent allows the antecedent to be true but doesnt 
have to be.
necessary condition
The cosequent impplies the apearance of a true antecedent.
~p
not p
p ^ q
p and q
p V q
p or q
p XOR q
p only if q
p == q
p is equivalent to q
p -> q
id p then q
p <--> q
p only if q, bi conditional
Three dots in a triangle
Therefore
upside down A
All
Backwards E
There exsists
union
Or
intersection
And
Commutative laws
a + b = b + a
associative laws
(a+b)+c = a+(b+c)
distributive laws
a(b+c) = ab + ac
identity laws
a + 0 = a
b * 1 = b
negation laws
~1 = 0
~0 = 1
double negative law
~(~a) = a
idempotent laws
a + a = a
b * b = b
universal bound laws
a + 1 = 1
b * 0 = 0
De morgan's laws
~(a + b) = ~a * ~b
~(c * d) = ~c + ~d
absorption laws
a + (b * a) = a
negations of t and c
~t = 0
~c = 1
vacuously true
all blue balls are small is true when there are no blue balls in the set.
Modus Ponens
p \rightarrow q
p
\therefore q
Modus Tollens
p \rightarrow q
~q
\therefore ~p
Elimination: valid argument form
p v q
~q
\therefore p
Transitivity: Valid Argument form
p \rightarrow q
q \rightarrow r
\therefore p \rightarrow r

